spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db:3306/delivery?useSSL=false&serverTimezone=UTC
    username: mysql_user
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
server:
  port: 8080
google:
  distance-matrix:
    api-key: